# NOTE: in NRF52840, using P0.13 to low the VCC and 3.3V can be shutoff
# NOTE: D2 / 017 (SDA) and D3 / 020 (SCL) are I2C pins
# refer to the pinout specs from Readme
meta:
  engine: 4.1.0
  version: 0.0.2
  author: Aditya

units: 
  kx: cx
  ky: cy
  padd_val: 5
  px: kx + padd_val
  py: ky + padd_val
  thumb_spread: 1.15kx

points:
  zones:
    matrix:
      key:
        padding: ky
        spread: kx

      rows:
        down:
          row_net: P5
        home:
          row_net: P4
        up:
          row_net: P0
        num:
          row_net: P1

      columns:
        outer:
          key:
            col_net: P20

        pinky:
          key:
            col_net: P19
            stagger: 0.2 ky
            origin: [0,-ky/2]

        ring:
          key:
            col_net: P18
            stagger: 0.3 ky
            origin: [0,-ky/2]

        middle:
          key:
            col_net: P10
            stagger: 0.3 ky
            origin: [0,-ky/2]

        index:
          key:
            col_net: P9
            stagger: -0.3 ky
            origin: [0,-ky/2]

        inner:
          key:
            col_net: P8
            stagger: -0.ky
            origin: [0,-ky/2]

    thumbs:
      key:
        padding: ky
        spread: thumb_spread
      anchor:
        ref: matrix_inner_down
        shift: [-1.5 kx, -1.15 ky]

      rows:
        cluster:
          row_net: P7

      columns:
        col1:
          key:
              col_net: P7
              origin: [-kx/2,-ky/2]
              splay: -5
        col2:
          key:
              col_net: P8
              origin: [-kx/2,-ky/2]
              splay: -10
        col3:
          key:
              col_net: P9
              origin: [-kx/2,-ky/2]
              splay: -10

# Rest of your outlines section remains the same
outlines:
  keycap_outlines:
    - what: rectangle
      where: true
      fillet: 2
      size: [kx-0.5,ky-0.5]

  _raw_keys_layout:
    - what: polygon
      operation: stack
      points:
        -  ref: thumbs_col3_cluster
           shift: [0.6kx, 0.6ky]
        -  ref: thumbs_col3_cluster
           shift: [0.6kx, -0.6ky]
        -  ref: thumbs_col3_cluster
           shift: [-0.4kx, -0.6ky]

        -  ref: thumbs_col2_cluster
           shift: [0.4thumb_spread, -0.6ky]
        -  ref: thumbs_col2_cluster
           shift: [-0.4thumb_spread, -0.6ky]

        -  ref: thumbs_col1_cluster
           shift: [0.4thumb_spread, -0.6ky]
        -  ref: thumbs_col1_cluster
           shift: [-0.6kx, -0.6ky]

        -  ref: matrix_outer_down
           shift: [1.6kx, -0.6ky]
        -  ref: matrix_outer_down
           shift: [0.6kx, -0.6ky]
        -  ref: matrix_outer_down
           shift: [-0.6kx, -0.6ky]

        -  ref: matrix_outer_num
           shift: [-0.6kx, 0.6ky]
        -  ref: matrix_outer_num
           shift: [0.4kx, 0.6ky]

        -  ref: matrix_pinky_num
           shift: [-0.5kx, 0.6ky]
        -  ref: matrix_pinky_num
           shift: [0.4kx, 0.6ky]

        -  ref: matrix_ring_num
           shift: [-0.5kx, 0.6ky]
        -  ref: matrix_ring_num
           shift: [0.4kx, 0.6ky]

        -  ref: matrix_middle_num
           shift: [-0.5kx, 0.6ky]
        -  ref: matrix_middle_num
           shift: [0.5kx, 0.6ky]

        -  ref: matrix_index_num
           shift: [-0.4kx, 0.6ky]
        -  ref: matrix_index_num
           shift: [0.5kx, 0.6ky]

        -  ref: matrix_inner_num
           shift: [-0.4kx, 0.6ky]
        -  ref: matrix_inner_num
           shift: [0.5kx, 0.6ky]

        -  ref: matrix_inner_num
           shift: [0.6kx, 0.4ky]
        -  ref: matrix_inner_num
           shift: [1.8kx, 0.4ky]

        -  ref: matrix_inner_down
           shift: [1.8kx, -0.6ky]

  board_outline:
      - what: outline
        name: _raw_keys_layout
        operation: stack
        fillet: 2

  preview:
    - what: outline
      name: board_outline
      operation: stack
    - what: outline
      name: keycap_outlines
      operation: stack

pcbs.aditya:
    template: kicad8 # Required, since footprints are KiCad 8 only
    outlines:
        main.outline: board_outline
        keycaps:
            outline: keycap_outlines
            layer: Eco1.User
    footprints:
        # diode:
        #     what: avocado/sod-123w
        #     where: true
        #     params:
        #         from: "{{name}}"
        #         to: "{{row_net}}"
        #     adjust:
        #         shift: [ -7.6, -1.6 ]
        #         rotate: 90
        diode:
            what: ceoloide/diode_tht_sod123
            where: true
            params:
                from: "{{name}}"
                to: "{{row_net}}"
                reversible: true
                include_tht: false
                diode_3dmodel_filename:  '${SCOTTO_KICAD}/3dmodels/ScottoKeebs_Components.3dshapes/Diode_SOD-123.step'
            adjust:
                shift: [ -7.6, -1.6 ]
                rotate: 90
        # choc:
        #     what: choc
        #     where: true
        #     params:
        #         keycaps: true
        #         reverse: true
        #         hotswap: true
        #         from: "{{col_net}}"
        #         to: "{{name}}"
        choc:
            what: ceoloide/switch_choc_v1_v2
            where: true
            params:
                reversible: true
                hotswap: true
                # If you are using LEDs you cannot use solder
                solder: false
                include_plated_holes: true
                include_keycap: false
                include_corner_marks: true
                # remove this later - after adding LEDs
                include_choc_v1_led_cutout_marks: true
                choc_v1_support: true
                choc_v2_support: false
                switch_3dmodel_filename: '${SCOTTO_KICAD}/3dmodels/ScottoKeebs_Choc.3dshapes/Choc_V1.step'
                hotswap_3dmodel_filename:  '${SCOTTO_KICAD}/3dmodels/ScottoKeebs_Hotswap.3dshapes/Choc_V1.step'
                from: "{{col_net}}"
                to: "{{name}}"
        # promicro:
        #     what: avocado/promicro_pretty
        #     where:
        #         ref: matrix_inner_home
        #     adjust:
        #         shift: [22, 6.5]
        #         rotate: -90
        promicro:
            what: ceoloide/mcu_supermini_nrf52840
            where:
                ref: matrix_inner_home
            params:
                reversible: true
                reverse_mount: false
                include_traces: true
                mcu_3dmodel_filename: '${SCOTTO_KICAD}/3dmodels/ScottoKeebs_MCU.3dshapes/Nice_Nano_V2_Flipped.step'
            adjust:
                shift: [22, 24]
            #     rotate: -90

        fillzone:
            what: ceoloide/utility_filled_zone
            params:
                side: 'F&B'
                net: 'GND'

        jst-s2b-ph-kl:
            what: avocado/jst-s2b-ph-kl
            where:
                ref: matrix_inner_down
                shift: [21, -2]
                rotate: 180
            params:
                neg: GND
        pcm12:
            what: avocado/pcm12
            where:
                ref: matrix_inner_down
                shift: [30.5, 3]
                rotate: 90
            params:
                from: pos
                to: RAW
        wuerth-434121025816:
            what: avocado/wuerth-434121025816
            where:
                ref: matrix_inner_down
                shift: [30, -6]
                rotate: 90
            params:
                r1: RST
                r2: GND
        front_text: &text
            what: avocado/text
            where: &textWhere
                ref: matrix_pinky_down
                shift: [12, -7]
            params: &textParams
                text: A keyboard for Aditya
                justify: left
        back_text:
            <<: *text
            where:
                <<: *textWhere
                shift: [27, -7]
            params:
                <<: *textParams
                layer: B.SilkS
                justify: left mirror
        # safeText:
        #     <<: *text
        #     what: josukey/keepout
        #     params:
        #         points:
        #             -   x: -0.5
        #                 y: -2
        #             -   x: 15.5
        #                 y: -2
        #             -   x: 15.5
        #                 y: 2
        #             -   x: -0.5
        #                 y: 2
        # peace: &icon
        #     what: josukey/peace
        #     where:
        #         ref: matrix_inner_down
        #         shift: [13, -6]
        #     params:
        #         scale: 2
        # love:
        #     <<: *icon
        #     what: josukey/love
        # safeIcon:
        #     <<: *icon
        #     what: josukey/keepout
        #     params:
        #         points:
        #             -   x: -0.5
        #                 y: -0.5
        #             -   x: 13.25
        #                 y: -0.5
        #             -   x: 13.25
        #                 y: 13.25
        #             -   x: -0.5
        #                 y: 13.25
