# NOTE: in NRF52840, using P0.13 to low the VCC and 3.3V can be shutoff
# NOTE: D2 / 017 (SDA) and D3 / 020 (SCL) are I2C pins
# refer to the pinout specs from Readme
meta:
  engine: 4.1.0
  author: Aditya

units: 
  kx: cx
  ky: cy
  padd_val: 5
  px: kx + padd_val
  py: ky + padd_val

  outer_boundary: 1.5

  thumb_spread: 1.05kx

  led_pos_x: 0 # Led X position relative to the switch center
  led_pos_y: -4.7 # Led Y position relative to the switch center
  led_rotation: 0 # Led rotation

  diode_pos_x: -7.3
  diode_pos_y: -2.85
  diode_roation: 90

  # right top edge - its a bit janky
  mcu_pos_x: ( 1.95kx+outer_boundary-8.9 ) + ( -outer_boundary - 2)
  mcu_pos_y: (0.6ky+outer_boundary-14) + ( -outer_boundary - 3)

  oled_pos_x: mcu_pos_x + 0
  oled_pos_y: mcu_pos_y - 3.5

  # relative to matrix_inner_home
  battery_pads_x: 15
  battery_pads_y: 5

  power_switch_x: ( 1.95kx+outer_boundary ) + ( -outer_boundary - 8.9 - 2)
  power_switch_y: (0.6ky+outer_boundary) + ( -outer_boundary - 0.30)

  # relative to matrix_inner_home
  reset_switch_x: 32.5
  reset_switch_y: 22
  reset_switch_rotate: -90

  # relative to matrix_inner_up
  board_info_x: 0.5kx + 4
  board_info_y: 0.5ky
  board_info_rotate: -90




points:
  zones:
    matrix:
      key:
        padding: ky
        spread: kx
      anchor:
        shift: [100, -100] # Fix KiCad placement

      rows:
        down:
          row_net: P18  
        home:
          row_net: P19
        up:
          row_net: P20
        num:
          row_net: P21

      columns:
        outer:
          key:
            col_net: P1
          rows:
            num.key:
              led_prev: LED_26
              led_next: LED_27
            up.key:
              led_prev: LED_15
              led_next: LED_16
            home.key:
              led_prev: LED_14
              led_next: LED_15
            down.key:
              led_prev: LED_3
              led_next: LED_4

        pinky:
          key:
            col_net: P0
            stagger: 0.2 ky
            origin: [0,-ky/2]
          rows:
            num.key:
              led_prev: LED_25
              led_next: LED_26
            up.key:
              led_prev: LED_16
              led_next: LED_17
            home.key:
              led_prev: LED_13
              led_next: LED_14
            down.key:
              led_prev: LED_4
              led_next: LED_5

        ring:
          key:
            col_net: P4
            stagger: 0.3 ky
            origin: [0,-ky/2]
          rows:
            num.key:
              led_prev: LED_24
              led_next: LED_25
            up.key:
              led_prev: LED_17
              led_next: LED_18
            home.key:
              led_prev: LED_12
              led_next: LED_13
            down.key:
              led_prev: LED_5
              led_next: LED_6

        middle:
          key:
            col_net: P5
            stagger: 0.3 ky
            origin: [0,-ky/2]
          rows:
            num.key:
              led_prev: LED_23
              led_next: LED_24
            up.key:
              led_prev: LED_18
              led_next: LED_19
            home.key:
              led_prev: LED_11
              led_next: LED_12
            down.key:
              led_prev: LED_6
              led_next: LED_7

        index:
          key:
            col_net: P7
            stagger: -0.3 ky
            origin: [0,-ky/2]
          rows:
            num.key:
              led_prev: LED_22
              led_next: LED_23
            up.key:
              led_prev: LED_19
              led_next: LED_20
            home.key:
              led_prev: LED_10
              led_next: LED_11
            down.key:
              led_prev: LED_7
              led_next: LED_8

        inner:
          key:
            col_net: P8
            stagger: -0.11 ky
            origin: [0,-ky/2]
          rows:
            num.key:
              led_prev: LED_21
              led_next: LED_22
            up.key:
              led_prev: LED_20
              led_next: LED_21
            home.key:
              led_prev: LED_9
              led_next: LED_10
            down.key:
              led_prev: LED_8
              led_next: LED_9

    thumbs:
      key:
        padding: ky
        spread: thumb_spread
      anchor:
        ref: matrix_inner_down
        shift: [-1.5 kx, -1.01 ky]

      rows:
        cluster:
          row_net: P15

      columns:
        col1:
          key:
            col_net: P5
            origin: [-kx/2,-ky/2]
            splay: -5
          rows:
            cluster.key:
              led_prev: LED_2
              led_next: LED_3
        col2:
          key:
            col_net: P7
            origin: [-kx/2,-ky/2]
            splay: -10
          rows:
            cluster.key:
              led_prev: LED_1
              led_next: LED_2
        col3:
          key:
            col_net: P8
            origin: [-kx/2,-ky/2]
            splay: -10
          rows:
            cluster.key:
              # This will be LED_0
              led_prev: P6
              led_next: LED_1

# Rest of your outlines section remains the same
outlines:
  keycap_outlines:
    - what: rectangle
      where: true
      fillet: 2
      size: [kx-0.5,ky-0.5]

  _raw_keys_layout:
    - what: polygon
      operation: stack
      points:
        # -  ref: thumbs_col3_cluster
        #    shift: [0.6kx+outer_boundary, 0.6ky+outer_boundary]
        -  ref: thumbs_col3_cluster
           shift: [0.6kx+outer_boundary, -0.6ky-outer_boundary]
        -  ref: thumbs_col3_cluster
           shift: [-0.4kx, -0.6ky-outer_boundary]

        -  ref: thumbs_col2_cluster
           shift: [0.4thumb_spread, -0.6ky-outer_boundary]
        -  ref: thumbs_col2_cluster
           shift: [-0.4thumb_spread, -0.6ky-outer_boundary]

        -  ref: thumbs_col1_cluster
           shift: [0.4thumb_spread, -0.6ky-outer_boundary]
        -  ref: thumbs_col1_cluster
           shift: [-0.6kx, -0.6ky-outer_boundary]

        -  ref: matrix_outer_down
           shift: [1.6kx, -0.6ky-outer_boundary]
        -  ref: matrix_outer_down
           shift: [0.6kx, -0.6ky-outer_boundary]
        -  ref: matrix_outer_down
           shift: [-0.6kx-outer_boundary, -0.6ky-outer_boundary]

        -  ref: matrix_outer_num
           shift: [-0.6kx-outer_boundary, 0.6ky+outer_boundary]
        -  ref: matrix_outer_num
           shift: [0.4kx, 0.6ky+outer_boundary]

        -  ref: matrix_pinky_num
           shift: [-0.5kx, 0.6ky+outer_boundary]
        -  ref: matrix_pinky_num
           shift: [0.4kx, 0.6ky+outer_boundary]

        -  ref: matrix_ring_num
           shift: [-0.5kx, 0.6ky+outer_boundary]
        -  ref: matrix_ring_num
           shift: [0.4kx, 0.6ky+outer_boundary]

        -  ref: matrix_middle_num
           shift: [-0.5kx, 0.6ky+outer_boundary]
        -  ref: matrix_middle_num
           shift: [0.5kx, 0.6ky+outer_boundary]

        -  ref: matrix_index_num
           shift: [-0.4kx, 0.6ky+outer_boundary]
        -  ref: matrix_index_num
           shift: [0.5kx, 0.6ky+outer_boundary]

        -  ref: matrix_inner_num
           shift: [-0.4kx, 0.6ky+outer_boundary]
        -  ref: matrix_inner_num
           shift: [0.5kx, 0.6ky+outer_boundary]

        -  ref: matrix_inner_num
           shift: [0.6kx, 0.6ky+outer_boundary]
        -  ref: matrix_inner_num
           shift: [1.95kx+outer_boundary, 0.6ky+outer_boundary]

        -  ref: matrix_inner_down
           shift: [1.95kx+outer_boundary, -0.6ky-5]

  board_outline:
    - what: outline
      name: _raw_keys_layout
      operation: stack
      fillet: 2

  preview:
    - what: outline
      name: board_outline
      operation: stack
    - what: outline
      name: keycap_outlines
      operation: stack

pcbs.StackOverChonk:
  template: kicad8 # Required, since footprints are KiCad 8 only
  outlines:
    main.outline: board_outline
    keycaps:
      outline: keycap_outlines
      layer: Eco1.User

  footprints:
    diode:
      what: ceoloide/diode_tht_sod123
      where: true
      params:
        from: "{{name}}"
        to: "{{row_net}}"
        reversible: true
        include_tht: false
        include_traces_vias: true
        # trace_distance: -0.5
        trace_distance: -1.1
        diode_3dmodel_filename: '${SCOTTO_KICAD}/3dmodels/ScottoKeebs_Components.3dshapes/Diode_SOD-123.step'
      adjust:
        shift: [ diode_pos_x, diode_pos_y ]
        rotate: diode_roation

    choc:
      what: ceoloide/switch_choc_v1_v2
      where: true
      params:
        reversible: true
        hotswap: true
        # If you are using LEDs you cannot use solder
        solder: false
        include_plated_holes: false
        include_keycap: false
        include_corner_marks: true
        # remove this later - after adding LEDs
        include_choc_v1_led_cutout_marks: true
        choc_v1_support: true
        choc_v2_support: false
        include_traces_vias: true
        hotswap_pads_same_side: false
        switch_3dmodel_filename: '${SCOTTO_KICAD}/3dmodels/ScottoKeebs_Choc.3dshapes/Choc_V1.step'
        switch_3dmodel_xyz_rotation: [0,0,180]
        hotswap_3dmodel_filename: '${SCOTTO_KICAD}/3dmodels/ScottoKeebs_Hotswap.3dshapes/Choc_V1.step'
        hotswap_3dmodel_xyz_rotation: [0,0,180]
        keycap_3dmodel_filename: '${SCOTTO_KICAD}/3dmodels/ScottoKeebs_CAD.3dshapes/Choc_1.00u_CAD.step'
        keycap_3dmodel_xyz_offset: [0, 0, 10]
        keycap_3dmodel_xyz_rotation: [0, 180, 90]
        from: "{{col_net}}"
        to: "{{name}}"

    promicro:
      what: ceoloide/mcu_supermini_nrf52840
      where:
        ref: matrix_inner_home
      params:
        reversible: true
        reverse_mount: true
        include_traces: true
        mcu_3dmodel_filename: '${SCOTTO_KICAD}/3dmodels/ScottoKeebs_MCU.3dshapes/Nice_Nano_V2_Flipped.step'
        mcu_3dmodel_xyz_offset: [0, 0, -7]
        mcu_3dmodel_xyz_rotation: [0, 180, 0]

      adjust:
        ref: matrix_inner_num
        shift: [mcu_pos_x, mcu_pos_y]

    oled_display:
      what: ceoloide/display_ssd1306
      where:
        ref: matrix_inner_num
      params:
        reversible: true
        include_traces: true
        SDA: P2
        SCL: P3
      adjust:
        shift: [oled_pos_x, oled_pos_y]

    per_key_leds_default:
      what: ceoloide/led_sk6812mini-e
      # where: true
      where:
        - /matrix_.*_up/
        - /matrix_.*_down/
      params:
        P1: VCC
        P2: "{{key.led_next}}" #DOUT
        P3: GND
        P4: "{{key.led_prev}}" #DIN
        reversible: true
        reverse_mount: true #(per-key LED)
        include_traces_vias: true
        side: F
        led_3dmodel_filename: '${SCOTTO_KICAD}/3dmodels/ScottoKeebs_Components.3dshapes/LED_SK6812MINI.step'
        led_3dmodel_xyz_rotation: [90, 0, 180]
      adjust:
        shift: [led_pos_x, led_pos_y]
        rotate: led_rotation

    # rotate alternate rows for easier routing
    per_key_leds_rotate_rows:
      $extends: pcbs.StackOverChonk.footprints.per_key_leds_default
      where:
        - /matrix_.*_num/
        - /matrix_.*_home/
        - /thumbs.*_cluster/
      adjust:
        rotate: led_rotation - 180

    fillzone:
      what: ceoloide/utility_filled_zone
      params:
        side: 'F&B'
        net: 'GND'

    battery_pads_front:
      what: battery_pad
      params:
        pos: pos
        neg: GND
        side: 'F'
        flip_pads: false
      where:
        ref: matrix_inner_home
        shift: [battery_pads_x, battery_pads_y]

    battery_pads_back:
      $extends: pcbs.StackOverChonk.footprints.battery_pads_front
      params:
        side: 'B'

    power_switch:
      what: ceoloide/power_switch_smd_side
      where:
        ref: matrix_inner_num
        shift: [power_switch_x, power_switch_y]
        rotate: 90
      params:
        side: 'B'
        reversible: true
        from: pos
        to: RAW
        invert_behavior: false
        switch_3dmodel_filename: '${SCOTTO_KICAD}/3dmodels/ScottoKeebs_Components.3dshapes/Switch_MSK12C02.step'
        switch_3dmodel_xyz_rotation: [0,0,90]

    reset_switch:
      what: ceoloide/reset_switch_smd_side
      where:
        ref: matrix_inner_down
        shift: [reset_switch_x, reset_switch_y]
        rotate: reset_switch_rotate
      params:
        side: F
        reversible: true
        include_bosses: true
        from: RST
        to: GND

    mounting_hole_top_left:
      what: ceoloide/mounting_hole_plated
      where:
        ref: matrix_pinky_num
        shift: [-kx/2, -ky/2]
      params:
        side: B
        outline: 0.7
        drill: 2.2

    mounting_hole_bottom_left:
      $extends: pcbs.StackOverChonk.footprints.mounting_hole_top_left
      where:
        ref: matrix_pinky_home


    mounting_hole_top_right:
      $extends: pcbs.StackOverChonk.footprints.mounting_hole_top_left
      where:
        ref: matrix_inner_num
        shift: [(-kx/2) - 0.5 , (-kx/2) + 2.2]

    mounting_hole_bottom_right:
      $extends: pcbs.StackOverChonk.footprints.mounting_hole_top_left
      where:
        ref: matrix_inner_home
        shift: [(-kx/2) - 0.5 , (-kx/2) + 2.2]

    mounting_hole_top_center:
      $extends: pcbs.StackOverChonk.footprints.mounting_hole_top_left
      where:
        ref: matrix_middle_home

    mounting_hole_bottom_center:
      $extends: pcbs.StackOverChonk.footprints.mounting_hole_top_left
      where:
        ref: matrix_middle_num


    pussy_cat:
      what: memes/pussy_cat
      where:
        ref: matrix_pinky_down
        shift: [8, -4]
      params:
        layer: 'F.SilkS'
        scale: 0.06
        flip: false

    confused_af:
      what: memes/confused_af
      where:
        ref: matrix_ring_down
        shift: [20, -3]
      params:
        scale: 0.08
        layer: 'B.SilkS'
        flip: true

    done_with_life:
      what: memes/done_with_life
      where:
        ref: matrix_inner_down
        shift: [37, 15]
      params:
        scale: 0.14
        layer: 'B.SilkS'
        flip: true

    thinking:
      what: memes/thinking
      where:
        ref: matrix_inner_down
        shift: [10, 15]
      params:
        scale: 0.032
        layer: 'F.SilkS'
        flip: false

    board_info:
      what: ceoloide/utility_text
      where:
        ref: matrix_inner_up
        shift: [board_info_x, board_info_y]
        rotate: board_info_rotate
      params:
        side: F
        text: "StackOverChonk - v0.1 pre-release\\ngithub.com/im-AMS/StackOverChonk"
        reversible: true
        knockout: false
        mirrored: true
